Vagrant.configure("2") do |config|
    machines = ["ansible", "file"]
  
    machines.each_with_index do |machine_name, i|
      config.vm.define machine_name do |node|
        node.vm.box = "ubuntu/focal64"
        node.vm.box_version = "20230803.0.0"
        
        # Calculate IP address for each machine
        ip_address = "192.168.50.#{i + 1}"
  
        node.vm.network "private_network", ip: ip_address
        
        node.vm.hostname = machine_name
        
        
        # Provisioning script to modify /etc/ssh/sshd_config
        node.vm.provision "shell", inline: <<-SHELL
          # Replace PasswordAuthentication no with PasswordAuthentication yes in /etc/ssh/sshd_config
          sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        SHELL
        
        # Install Ansible and sshpass on the "ansible" machine
        if machine_name == "ansible"
          node.vm.provision "shell", inline: <<-SHELL
            # Install Ansible and sshpass
            sudo apt-get install -y ansible sshpass
          SHELL
        end
        
        # Provision the script to change XKBLAYOUT
        node.vm.provision "shell", inline: <<-SHELL
          # Replace XKBLAYOUT="us" with XKBLAYOUT="tr" in /etc/default/keyboard
          sudo sed -i 's/XKBLAYOUT="us"/XKBLAYOUT="tr"/' /etc/default/keyboard
        SHELL
  
        # Copy ansible_hosts file to /etc/ansible/hosts on "ansible" machine
        if machine_name == "ansible"
          node.vm.provision "file", source: "ansible_hosts", destination: "/vagrant/"
          node.vm.provision "shell", inline: <<-SHELL
            sudo cat /vagrant/ansible_hosts >> /etc/ansible/hosts
          SHELL
          
              
        end
      end
    end
  end